# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-06-02 22:55:45
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # Matlab Cholera Risk Model_Jul 2022

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(cellSize="0.0083333333", extent="88.0105667114258 20.7394450887048 92.668900044759 26.6311117553712 GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", mask="D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\BGD_Administrative Boundary\\BGD_adm0_1km.tif", 
                          outputCoordinateSystem="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]"):
        
        BD_Elevation_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Elevation\\BD_Elevation.tif")
        
        Elevation_2_ = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Elevation"
        
        LST_06_2022_datafilled_clipped_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Temperature\\Monthly Temperature\\LST_06_2022_datafilled_clipped.tif")
        
        MODIS_LST_JUN_2000_2020_Final_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Temperature\\NOAA_Long Term Average Temperature_1990_2019\\MODIS_LST_JUN_2000_2020_Final.tif")
        
        BGD_adm0_1km_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\BGD_Administrative Boundary\\BGD_adm0_1km.tif")
        
        JUN_2022_2_ = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022"
        
        Average_Temperature_Prediction_ENS01_10_Jul_2022_k_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Temperature Forecast\\Average_Temperature_Prediction_ENS01_10_Jul_2022_k.tif")
        
        JUL_2022_2_ = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022"
        
        IMERG_Total_Rainfall_mm_06_2022_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Rainfall\\Rainfall Monthly\\IMERG_Total Rainfall_mm_06_2022.tif")
        
        IMERG_Avg_Rainfall_Jun_2000_2020_Final_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Rainfall\\Rainfall Long Term Average\\IMERG_2001_2020\\IMERG_Avg_Rainfall_Jun_2000_2020_Final.tif")
        
        JUN_2022 = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022"
        
        Average_Total_Rain_Prediction_ENS01_10_Jul_2022_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Rainfall Forecast\\Average_Total_Rain_Prediction_ENS01_10_Jul_2022.tif")
        
        JUL_2022 = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022"
        
        Cholera_Jun_avg_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Previous_Cholera\\Cholera_Jun_avg.tif")
        
        June = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Previous_Cholera\\June"
        
        gpw_v4_population_density_rev11_2020_30_sec_tif = arcpy.Raster("D:\\RFF-GABS Project\\Bangladesh\\Input_BD\\Population Density 2020\\gpw-v4-population-density-rev11_2020_30_sec_tif\\gpw_v4_population_density_rev11_2020_30_sec.tif")
        
        Population = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Population"

        # Process: Raster Calculator (30) (Raster Calculator) (sa)
        Elevation_risk_4_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Elevation\\Elevation_risk_4.tif"
        Raster_Calculator_30_ = Elevation_risk_4_tif
        Elevation_risk_4_tif = Con((BD_Elevation_tif   <=  5), 4)
        Elevation_risk_4_tif.save(Raster_Calculator_30_)


        # Process: Raster Calculator (32) (Raster Calculator) (sa)
        Elevation_risk_3_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Elevation\\Elevation_risk_3.tif"
        Raster_Calculator_32_ = Elevation_risk_3_tif
        Elevation_risk_3_tif = Con((BD_Elevation_tif   >  5) & (BD_Elevation_tif  <=  8), 3)
        Elevation_risk_3_tif.save(Raster_Calculator_32_)


        # Process: Raster Calculator (31) (Raster Calculator) (sa)
        Elevation_risk_2_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Elevation\\Elevation_risk_2.tif"
        Raster_Calculator_31_ = Elevation_risk_2_tif
        Elevation_risk_2_tif = Con((BD_Elevation_tif   >  8) & (BD_Elevation_tif  <=  15), 2)
        Elevation_risk_2_tif.save(Raster_Calculator_31_)


        # Process: Raster Calculator (34) (Raster Calculator) (sa)
        Elevation_risk_0_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Elevation\\Elevation_risk_0.tif"
        Raster_Calculator_34_ = Elevation_risk_0_tif
        Elevation_risk_0_tif = Con((BD_Elevation_tif   >  30), 0)
        Elevation_risk_0_tif.save(Raster_Calculator_34_)


        # Process: Raster Calculator (33) (Raster Calculator) (sa)
        Elevation_risk_1_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Elevation\\Elevation_risk_1.tif"
        Raster_Calculator_33_ = Elevation_risk_1_tif
        Elevation_risk_1_tif = Con((BD_Elevation_tif   >  15) & (BD_Elevation_tif  <=  30), 1)
        Elevation_risk_1_tif.save(Raster_Calculator_33_)


        # Process: Mosaic To New Raster (6) (Mosaic To New Raster) (management)
        Elevation_Risk_tif = arcpy.management.MosaicToNewRaster(input_rasters=[Elevation_risk_4_tif, Elevation_risk_3_tif, Elevation_risk_2_tif, Elevation_risk_0_tif, Elevation_risk_1_tif], output_location=Elevation_2_, raster_dataset_name_with_extension="Elevation_Risk.tif", pixel_type="16_BIT_UNSIGNED", cellsize=0.0083333333, number_of_bands=1, mosaic_method="MEAN")[0]
        Elevation_Risk_tif = arcpy.Raster(Elevation_Risk_tif)

        # Process: Resample (4) (Resample) (management)
        Resample_Monthly_Temp_06_2022_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Resample_Monthly_Temp_06_2022.tif"
        arcpy.management.Resample(in_raster=LST_06_2022_datafilled_clipped_tif, out_raster=Resample_Monthly_Temp_06_2022_tif, cell_size="0.0083333333 0.0083333333", resampling_type="BILINEAR")
        Resample_Monthly_Temp_06_2022_tif = arcpy.Raster(Resample_Monthly_Temp_06_2022_tif)

        # Process: Resample (3) (Resample) (management)
        Resample_LongTerm_Avg_Temp_06_2000_2020_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Resample_LongTerm_Avg_Temp_06_2000_2020.tif"
        arcpy.management.Resample(in_raster=MODIS_LST_JUN_2000_2020_Final_tif, out_raster=Resample_LongTerm_Avg_Temp_06_2000_2020_tif, cell_size="0.0083333333 0.0083333333", resampling_type="BILINEAR")
        Resample_LongTerm_Avg_Temp_06_2000_2020_tif = arcpy.Raster(Resample_LongTerm_Avg_Temp_06_2000_2020_tif)

        # Process: Raster Calculator (6) (Raster Calculator) (sa)
        Temperature_anomaly_Jun_2022_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Temperature_anomaly_Jun_2022.tif"
        Raster_Calculator_6_ = Temperature_anomaly_Jun_2022_tif
        Temperature_anomaly_Jun_2022_tif = (Resample_Monthly_Temp_06_2022_tif) - (Resample_LongTerm_Avg_Temp_06_2000_2020_tif)
        Temperature_anomaly_Jun_2022_tif.save(Raster_Calculator_6_)


        # Process: Extract by Mask (3) (Extract by Mask) (sa)
        Temperature_anomaly_Jun_2022_clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Temperature_anomaly_Jun_2022_clip.tif"
        Extract_by_Mask_3_ = Temperature_anomaly_Jun_2022_clip_tif
        Temperature_anomaly_Jun_2022_clip_tif = arcpy.sa.ExtractByMask(Temperature_anomaly_Jun_2022_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Temperature_anomaly_Jun_2022_clip_tif.save(Extract_by_Mask_3_)


        # Process: Raster Calculator (10) (Raster Calculator) (sa)
        Temp_Jun_2022_Risk_1_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Temp_Jun_2022_Risk_1.tif"
        Raster_Calculator_10_ = Temp_Jun_2022_Risk_1_tif
        Temp_Jun_2022_Risk_1_tif = Con((Temperature_anomaly_Jun_2022_clip_tif  <  0) & (Temperature_anomaly_Jun_2022_clip_tif   >=  - 1.5), 1)
        Temp_Jun_2022_Risk_1_tif.save(Raster_Calculator_10_)


        # Process: Raster Calculator (25) (Raster Calculator) (sa)
        Temp_Jun_2022_Risk_2_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Temp_Jun_2022_Risk_2.tif"
        Raster_Calculator_25_ = Temp_Jun_2022_Risk_2_tif
        Temp_Jun_2022_Risk_2_tif = Con((Temperature_anomaly_Jun_2022_clip_tif  <  -1.5) & (Temperature_anomaly_Jun_2022_clip_tif  >=  -3), 2)
        Temp_Jun_2022_Risk_2_tif.save(Raster_Calculator_25_)


        # Process: Raster Calculator (9) (Raster Calculator) (sa)
        Temp_Jun_2022_Risk_0_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Temp_Jun_2022_Risk_0.tif"
        Raster_Calculator_9_ = Temp_Jun_2022_Risk_0_tif
        Temp_Jun_2022_Risk_0_tif = Con((Temperature_anomaly_Jun_2022_clip_tif  >  0), 0)
        Temp_Jun_2022_Risk_0_tif.save(Raster_Calculator_9_)


        # Process: Raster Calculator (26) (Raster Calculator) (sa)
        Temp_Jun_2022_Risk_3_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Temp_Jun_2022_Risk_3.tif"
        Raster_Calculator_26_ = Temp_Jun_2022_Risk_3_tif
        Temp_Jun_2022_Risk_3_tif = Con((Temperature_anomaly_Jun_2022_clip_tif   <  -3) & (Temperature_anomaly_Jun_2022_clip_tif   >=   -5 ), 3)
        Temp_Jun_2022_Risk_3_tif.save(Raster_Calculator_26_)


        # Process: Raster Calculator (27) (Raster Calculator) (sa)
        Temp_Jun_2022_Risk_4_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature\\JUN_2022\\Temp_Jun_2022_Risk_4.tif"
        Raster_Calculator_27_ = Temp_Jun_2022_Risk_4_tif
        Temp_Jun_2022_Risk_4_tif = Con((Temperature_anomaly_Jun_2022_clip_tif   <  -5  ), 4)
        Temp_Jun_2022_Risk_4_tif.save(Raster_Calculator_27_)


        # Process: Mosaic To New Raster (2) (Mosaic To New Raster) (management)
        T_Risk_Jun_2022_tif = arcpy.management.MosaicToNewRaster(input_rasters=[Temp_Jun_2022_Risk_1_tif, Temp_Jun_2022_Risk_2_tif, Temp_Jun_2022_Risk_0_tif, Temp_Jun_2022_Risk_3_tif, Temp_Jun_2022_Risk_4_tif], output_location=JUN_2022_2_, raster_dataset_name_with_extension="T_Risk_Jun_2022.tif", pixel_type="8_BIT_UNSIGNED", cellsize=0.0083333333, number_of_bands=1, mosaic_method="MEAN")[0]
        T_Risk_Jun_2022_tif = arcpy.Raster(T_Risk_Jun_2022_tif)

        # Process: Extract by Mask (5) (Extract by Mask) (sa)
        Temperature_Risk_Jun_2022_clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Temperature\\JUN_2022\\Temperature_Risk_Jun_2022_clip.tif"
        Extract_by_Mask_5_ = Temperature_Risk_Jun_2022_clip_tif
        Temperature_Risk_Jun_2022_clip_tif = arcpy.sa.ExtractByMask(T_Risk_Jun_2022_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Temperature_Risk_Jun_2022_clip_tif.save(Extract_by_Mask_5_)


        # Process: Resample (5) (Resample) (management)
        Temp_F_Jul_2022_Resample_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\Temp_F_Jul_2022_Resample.tif"
        arcpy.management.Resample(in_raster=Average_Temperature_Prediction_ENS01_10_Jul_2022_k_tif, out_raster=Temp_F_Jul_2022_Resample_tif, cell_size="0.0083333333 0.0083333333", resampling_type="BILINEAR")
        Temp_F_Jul_2022_Resample_tif = arcpy.Raster(Temp_F_Jul_2022_Resample_tif)

        # Process: Raster Calculator (Raster Calculator) (sa)
        Temp_F_Jul_2022_C_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\Temp_F_Jul_2022_C.tif"
        Raster_Calculator = Temp_F_Jul_2022_C_tif
        Temp_F_Jul_2022_C_tif = Temp_F_Jul_2022_Resample_tif - 273.15
        Temp_F_Jul_2022_C_tif.save(Raster_Calculator)


        # Process: Extract by Mask (14) (Extract by Mask) (sa)
        Jul_2022_BD_C_Clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\Jul_2022_BD_C_Clip.tif"
        Extract_by_Mask_14_ = Jul_2022_BD_C_Clip_tif
        Jul_2022_BD_C_Clip_tif = arcpy.sa.ExtractByMask(Temp_F_Jul_2022_C_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Jul_2022_BD_C_Clip_tif.save(Extract_by_Mask_14_)


        # Process: Raster Calculator (7) (Raster Calculator) (sa)
        TF_Jul_22_Risk_4_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\TF_Jul_22_Risk_4.tif"
        Raster_Calculator_7_ = TF_Jul_22_Risk_4_tif
        TF_Jul_22_Risk_4_tif = Con((Jul_2022_BD_C_Clip_tif     <=  25), 4)
        TF_Jul_22_Risk_4_tif.save(Raster_Calculator_7_)


        # Process: Raster Calculator (35) (Raster Calculator) (sa)
        TF_Jul_22_Risk_3_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\TF_Jul_22_Risk_3.tif"
        Raster_Calculator_35_ = TF_Jul_22_Risk_3_tif
        TF_Jul_22_Risk_3_tif = Con((Jul_2022_BD_C_Clip_tif   >  25) & (Jul_2022_BD_C_Clip_tif  <=  27), 3)
        TF_Jul_22_Risk_3_tif.save(Raster_Calculator_35_)


        # Process: Raster Calculator (8) (Raster Calculator) (sa)
        TF_Jul_22_Risk_2_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\TF_Jul_22_Risk_2.tif"
        Raster_Calculator_8_ = TF_Jul_22_Risk_2_tif
        TF_Jul_22_Risk_2_tif = Con((Jul_2022_BD_C_Clip_tif   >  27) & (Jul_2022_BD_C_Clip_tif  <=  28), 2)
        TF_Jul_22_Risk_2_tif.save(Raster_Calculator_8_)


        # Process: Raster Calculator (42) (Raster Calculator) (sa)
        TF_Jul_22_Risk_0_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\TF_Jul_22_Risk_0.tif"
        Raster_Calculator_42_ = TF_Jul_22_Risk_0_tif
        TF_Jul_22_Risk_0_tif = Con((Jul_2022_BD_C_Clip_tif     >   29), 0)
        TF_Jul_22_Risk_0_tif.save(Raster_Calculator_42_)


        # Process: Raster Calculator (41) (Raster Calculator) (sa)
        TF_Jul_22_Risk_1_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Temperature Forecast\\JUL_2022\\TF_Jul_22_Risk_1.tif"
        Raster_Calculator_41_ = TF_Jul_22_Risk_1_tif
        TF_Jul_22_Risk_1_tif = Con((Jul_2022_BD_C_Clip_tif   >  28) & (Jul_2022_BD_C_Clip_tif  <= 29), 1)
        TF_Jul_22_Risk_1_tif.save(Raster_Calculator_41_)


        # Process: Mosaic To New Raster (8) (Mosaic To New Raster) (management)
        Temp_F_Jul_2022_tif = arcpy.management.MosaicToNewRaster(input_rasters=[TF_Jul_22_Risk_4_tif, TF_Jul_22_Risk_3_tif, TF_Jul_22_Risk_2_tif, TF_Jul_22_Risk_0_tif, TF_Jul_22_Risk_1_tif], output_location=JUL_2022_2_, raster_dataset_name_with_extension="Temp_F_Jul_2022.tif", cellsize=0.0083333333, number_of_bands=1, mosaic_method="MEAN")[0]
        Temp_F_Jul_2022_tif = arcpy.Raster(Temp_F_Jul_2022_tif)

        # Process: Extract by Mask (15) (Extract by Mask) (sa)
        Temp_Forecast_Jul_2022_clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Temperature Forecast\\JUL_2022\\Temp_Forecast_Jul_2022_clip.tif"
        Extract_by_Mask_15_ = Temp_Forecast_Jul_2022_clip_tif
        Temp_Forecast_Jul_2022_clip_tif = arcpy.sa.ExtractByMask(Temp_F_Jul_2022_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Temp_Forecast_Jul_2022_clip_tif.save(Extract_by_Mask_15_)


        # Process: Resample (2) (Resample) (management)
        Resample_Monthly_Total_Rainfall_06_2022_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Resample_Monthly_Total_Rainfall_06_2022.tif"
        arcpy.management.Resample(in_raster=IMERG_Total_Rainfall_mm_06_2022_tif, out_raster=Resample_Monthly_Total_Rainfall_06_2022_tif, cell_size="0.0083333333 0.0083333333", resampling_type="BILINEAR")
        Resample_Monthly_Total_Rainfall_06_2022_tif = arcpy.Raster(Resample_Monthly_Total_Rainfall_06_2022_tif)

        # Process: Extract by Mask (8) (Extract by Mask) (sa)
        Rainfall_Jun_22_Clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Rainfall_Jun_22_Clip.tif"
        Extract_by_Mask_8_ = Rainfall_Jun_22_Clip_tif
        Rainfall_Jun_22_Clip_tif = arcpy.sa.ExtractByMask(Resample_Monthly_Total_Rainfall_06_2022_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Rainfall_Jun_22_Clip_tif.save(Extract_by_Mask_8_)


        # Process: Resample (Resample) (management)
        Resample_LongTerm_Avg_06_2001_2020_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Resample_LongTerm_Avg_06_2001_2020.tif"
        arcpy.management.Resample(in_raster=IMERG_Avg_Rainfall_Jun_2000_2020_Final_tif, out_raster=Resample_LongTerm_Avg_06_2001_2020_tif, cell_size="0.0083333333 0.0083333333", resampling_type="BILINEAR")
        Resample_LongTerm_Avg_06_2001_2020_tif = arcpy.Raster(Resample_LongTerm_Avg_06_2001_2020_tif)

        # Process: Extract by Mask (7) (Extract by Mask) (sa)
        Avg_Rainfall_Jun_2001_2020_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Avg_Rainfall_Jun_2001_2020.tif"
        Extract_by_Mask_7_ = Avg_Rainfall_Jun_2001_2020_tif
        Avg_Rainfall_Jun_2001_2020_tif = arcpy.sa.ExtractByMask(Resample_LongTerm_Avg_06_2001_2020_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Avg_Rainfall_Jun_2001_2020_tif.save(Extract_by_Mask_7_)


        # Process: Raster Calculator (11) (Raster Calculator) (sa)
        Rain_Anomaly_06_2022_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Rain_Anomaly_06_2022.tif"
        Raster_Calculator_11_ = Rain_Anomaly_06_2022_tif
        Rain_Anomaly_06_2022_tif = (Rainfall_Jun_22_Clip_tif) - (Avg_Rainfall_Jun_2001_2020_tif)
        Rain_Anomaly_06_2022_tif.save(Raster_Calculator_11_)


        # Process: Extract by Mask (4) (Extract by Mask) (sa)
        Rain_Anomaly_06_2022_clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Rain_Anomaly_06_2022_clip.tif"
        Extract_by_Mask_4_ = Rain_Anomaly_06_2022_clip_tif
        Rain_Anomaly_06_2022_clip_tif = arcpy.sa.ExtractByMask(Rain_Anomaly_06_2022_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Rain_Anomaly_06_2022_clip_tif.save(Extract_by_Mask_4_)


        # Process: Raster Calculator (16) (Raster Calculator) (sa)
        Jun_22_rain_risk_1_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Jun_22_rain_risk_1.tif"
        Raster_Calculator_16_ = Jun_22_rain_risk_1_tif
        Jun_22_rain_risk_1_tif = Con((Rain_Anomaly_06_2022_clip_tif  <= 50) & (Rain_Anomaly_06_2022_clip_tif  >   0), 1)    
        Jun_22_rain_risk_1_tif.save(Raster_Calculator_16_)


        # Process: Raster Calculator (12) (Raster Calculator) (sa)
        Jun_22_rain_risk_0_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Jun_22_rain_risk_0.tif"
        Raster_Calculator_12_ = Jun_22_rain_risk_0_tif
        Jun_22_rain_risk_0_tif = Con((Rain_Anomaly_06_2022_clip_tif    <=   0), 0)
        Jun_22_rain_risk_0_tif.save(Raster_Calculator_12_)


        # Process: Raster Calculator (13) (Raster Calculator) (sa)
        Jun_22_rain_risk_2_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Jun_22_rain_risk_2.tif"
        Raster_Calculator_13_ = Jun_22_rain_risk_2_tif
        Jun_22_rain_risk_2_tif = Con((Rain_Anomaly_06_2022_clip_tif > 50) & (Rain_Anomaly_06_2022_clip_tif  <=   100), 2)
        Jun_22_rain_risk_2_tif.save(Raster_Calculator_13_)


        # Process: Raster Calculator (14) (Raster Calculator) (sa)
        Jun_22_rain_risk_3_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Jun_22_rain_risk_3.tif"
        Raster_Calculator_14_ = Jun_22_rain_risk_3_tif
        Jun_22_rain_risk_3_tif = Con((Rain_Anomaly_06_2022_clip_tif > 100) & (Rain_Anomaly_06_2022_clip_tif  <= 200), 3)
        Jun_22_rain_risk_3_tif.save(Raster_Calculator_14_)


        # Process: Raster Calculator (15) (Raster Calculator) (sa)
        Jun_22_rain_risk_4_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall\\JUN_2022\\Jun_22_rain_risk_4.tif"
        Raster_Calculator_15_ = Jun_22_rain_risk_4_tif
        Jun_22_rain_risk_4_tif = Con((Rain_Anomaly_06_2022_clip_tif   >  200), 4)
        Jun_22_rain_risk_4_tif.save(Raster_Calculator_15_)


        # Process: Mosaic To New Raster (3) (Mosaic To New Raster) (management)
        Rain_Risk_Jun_2022_tif = arcpy.management.MosaicToNewRaster(input_rasters=[Jun_22_rain_risk_1_tif, Jun_22_rain_risk_0_tif, Jun_22_rain_risk_2_tif, Jun_22_rain_risk_3_tif, Jun_22_rain_risk_4_tif], output_location=JUN_2022, raster_dataset_name_with_extension="Rain_Risk_Jun_2022.tif", pixel_type="8_BIT_UNSIGNED", cellsize=0.0083333333, number_of_bands=1, mosaic_method="MEAN")[0]
        Rain_Risk_Jun_2022_tif = arcpy.Raster(Rain_Risk_Jun_2022_tif)

        # Process: Extract by Mask (6) (Extract by Mask) (sa)
        Rain_Anomaly_Risk_Jun_2022_clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Rainfall\\JUN_2022\\Rain_Anomaly_Risk_Jun_2022_clip.tif"
        Extract_by_Mask_6_ = Rain_Anomaly_Risk_Jun_2022_clip_tif
        Rain_Anomaly_Risk_Jun_2022_clip_tif = arcpy.sa.ExtractByMask(Rain_Risk_Jun_2022_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Rain_Anomaly_Risk_Jun_2022_clip_tif.save(Extract_by_Mask_6_)


        # Process: Resample (6) (Resample) (management)
        Rain_F_Jul_2022_Resample_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_F_Jul_2022_Resample.tif"
        arcpy.management.Resample(in_raster=Average_Total_Rain_Prediction_ENS01_10_Jul_2022_tif, out_raster=Rain_F_Jul_2022_Resample_tif, cell_size="0.0083333333 0.0083333333", resampling_type="BILINEAR")
        Rain_F_Jul_2022_Resample_tif = arcpy.Raster(Rain_F_Jul_2022_Resample_tif)

        # Process: Extract by Mask (9) (Extract by Mask) (sa)
        Rain_Forecast_Jul_2022_Clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_Forecast_Jul_2022_Clip.tif"
        Extract_by_Mask_9_ = Rain_Forecast_Jul_2022_Clip_tif
        Rain_Forecast_Jul_2022_Clip_tif = arcpy.sa.ExtractByMask(Rain_F_Jul_2022_Resample_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Rain_Forecast_Jul_2022_Clip_tif.save(Extract_by_Mask_9_)


        # Process: Raster Calculator (17) (Raster Calculator) (sa)
        Rain_Forecast_Risk_Jul_22_4_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_Forecast_Risk_Jul_22_4.tif"
        Raster_Calculator_17_ = Rain_Forecast_Risk_Jul_22_4_tif
        Rain_Forecast_Risk_Jul_22_4_tif = Con((Rain_Forecast_Jul_2022_Clip_tif     >    600), 4)
        Rain_Forecast_Risk_Jul_22_4_tif.save(Raster_Calculator_17_)


        # Process: Raster Calculator (19) (Raster Calculator) (sa)
        Rain_Forecast_Risk_Jul_22_3_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_Forecast_Risk_Jul_22_3.tif"
        Raster_Calculator_19_ = Rain_Forecast_Risk_Jul_22_3_tif
        Rain_Forecast_Risk_Jul_22_3_tif = Con((Rain_Forecast_Jul_2022_Clip_tif   >  450) & (Rain_Forecast_Jul_2022_Clip_tif  <=  600), 3)
        Rain_Forecast_Risk_Jul_22_3_tif.save(Raster_Calculator_19_)


        # Process: Raster Calculator (18) (Raster Calculator) (sa)
        Rain_Forecast_Risk_Jul_22_2_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_Forecast_Risk_Jul_22_2.tif"
        Raster_Calculator_18_ = Rain_Forecast_Risk_Jul_22_2_tif
        Rain_Forecast_Risk_Jul_22_2_tif = Con((Rain_Forecast_Jul_2022_Clip_tif   >  300) & (Rain_Forecast_Jul_2022_Clip_tif  <=  450), 2)
        Rain_Forecast_Risk_Jul_22_2_tif.save(Raster_Calculator_18_)


        # Process: Raster Calculator (21) (Raster Calculator) (sa)
        Rain_Forecast_Risk_Jul_22_0_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_Forecast_Risk_Jul_22_0.tif"
        Raster_Calculator_21_ = Rain_Forecast_Risk_Jul_22_0_tif
        Rain_Forecast_Risk_Jul_22_0_tif = Con((Rain_Forecast_Jul_2022_Clip_tif   >  0) & (Rain_Forecast_Jul_2022_Clip_tif  <=  260), 0)
        Rain_Forecast_Risk_Jul_22_0_tif.save(Raster_Calculator_21_)


        # Process: Raster Calculator (20) (Raster Calculator) (sa)
        Rain_Forecast_Risk_Jul_22_1_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_Forecast_Risk_Jul_22_1.tif"
        Raster_Calculator_20_ = Rain_Forecast_Risk_Jul_22_1_tif
        Rain_Forecast_Risk_Jul_22_1_tif = Con((Rain_Forecast_Jul_2022_Clip_tif   >  260) & (Rain_Forecast_Jul_2022_Clip_tif  <=  300), 1)
        Rain_Forecast_Risk_Jul_22_1_tif.save(Raster_Calculator_20_)


        # Process: Mosaic To New Raster (4) (Mosaic To New Raster) (management)
        Rain_F_Risk_Jul_2022_tif = arcpy.management.MosaicToNewRaster(input_rasters=[Rain_Forecast_Risk_Jul_22_4_tif, Rain_Forecast_Risk_Jul_22_3_tif, Rain_Forecast_Risk_Jul_22_2_tif, Rain_Forecast_Risk_Jul_22_0_tif, Rain_Forecast_Risk_Jul_22_1_tif], output_location=JUL_2022, raster_dataset_name_with_extension="Rain_F_Risk_Jul_2022.tif", cellsize=0.0083333333, number_of_bands=1, mosaic_method="MEAN")[0]
        Rain_F_Risk_Jul_2022_tif = arcpy.Raster(Rain_F_Risk_Jul_2022_tif)

        # Process: Extract by Mask (12) (Extract by Mask) (sa)
        Rain_F_Risk_Jul_2022_clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Rainfall Forecast\\JUL_2022\\Rain_F_Risk_Jul_2022_clip.tif"
        Extract_by_Mask_12_ = Rain_F_Risk_Jul_2022_clip_tif
        Rain_F_Risk_Jul_2022_clip_tif = arcpy.sa.ExtractByMask(Rain_F_Risk_Jul_2022_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Rain_F_Risk_Jul_2022_clip_tif.save(Extract_by_Mask_12_)


        # Process: Raster Calculator (43) (Raster Calculator) (sa)
        Avg_Jun_Cholera_Risk_0_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Previous_Cholera\\June\\Avg_Jun_Cholera_Risk_0.tif"
        Raster_Calculator_43_ = Avg_Jun_Cholera_Risk_0_tif
        Avg_Jun_Cholera_Risk_0_tif = Con((Cholera_Jun_avg_tif     <=   1), 0)
        Avg_Jun_Cholera_Risk_0_tif.save(Raster_Calculator_43_)


        # Process: Raster Calculator (45) (Raster Calculator) (sa)
        Avg_Jun_Cholera_Risk_1_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Previous_Cholera\\June\\Avg_Jun_Cholera_Risk_1.tif"
        Raster_Calculator_45_ = Avg_Jun_Cholera_Risk_1_tif
        Avg_Jun_Cholera_Risk_1_tif = Con((Cholera_Jun_avg_tif   >  1) & (Cholera_Jun_avg_tif  <=  6), 1)
        Avg_Jun_Cholera_Risk_1_tif.save(Raster_Calculator_45_)


        # Process: Raster Calculator (44) (Raster Calculator) (sa)
        Avg_Jun_Cholera_Risk_2_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Previous_Cholera\\June\\Avg_Jun_Cholera_Risk_2.tif"
        Raster_Calculator_44_ = Avg_Jun_Cholera_Risk_2_tif
        Avg_Jun_Cholera_Risk_2_tif = Con((Cholera_Jun_avg_tif   >  6) & (Cholera_Jun_avg_tif  <=  9), 2)
        Avg_Jun_Cholera_Risk_2_tif.save(Raster_Calculator_44_)


        # Process: Raster Calculator (47) (Raster Calculator) (sa)
        Avg_Jun_Cholera_Risk_4_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Previous_Cholera\\June\\Avg_Jun_Cholera_Risk_4.tif"
        Raster_Calculator_47_ = Avg_Jun_Cholera_Risk_4_tif
        Avg_Jun_Cholera_Risk_4_tif = Con((Cholera_Jun_avg_tif   >  12), 4)
        Avg_Jun_Cholera_Risk_4_tif.save(Raster_Calculator_47_)


        # Process: Raster Calculator (46) (Raster Calculator) (sa)
        Avg_Jun_Cholera_Risk_3_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Previous_Cholera\\June\\Avg_Jun_Cholera_Risk_3.tif"
        Raster_Calculator_46_ = Avg_Jun_Cholera_Risk_3_tif
        Avg_Jun_Cholera_Risk_3_tif = Con((Cholera_Jun_avg_tif   >  9) & (Cholera_Jun_avg_tif  <=  12), 3)
        Avg_Jun_Cholera_Risk_3_tif.save(Raster_Calculator_46_)


        # Process: Mosaic To New Raster (9) (Mosaic To New Raster) (management)
        Jun_avg_Cholera_Risk_tif = arcpy.management.MosaicToNewRaster(input_rasters=[Avg_Jun_Cholera_Risk_0_tif, Avg_Jun_Cholera_Risk_1_tif, Avg_Jun_Cholera_Risk_2_tif, Avg_Jun_Cholera_Risk_4_tif, Avg_Jun_Cholera_Risk_3_tif], output_location=June, raster_dataset_name_with_extension="Jun_avg_Cholera_Risk.tif", cellsize=0.0083333333, number_of_bands=1, mosaic_method="MEAN")[0]
        Jun_avg_Cholera_Risk_tif = arcpy.Raster(Jun_avg_Cholera_Risk_tif)

        # Process: Extract by Mask (16) (Extract by Mask) (sa)
        Jun_avg_Cholera_Risk_clip_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Previous_Cholera\\June\\Jun_avg_Cholera_Risk_clip.tif"
        Extract_by_Mask_16_ = Jun_avg_Cholera_Risk_clip_tif
        Jun_avg_Cholera_Risk_clip_tif = arcpy.sa.ExtractByMask(Jun_avg_Cholera_Risk_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        Jun_avg_Cholera_Risk_clip_tif.save(Extract_by_Mask_16_)


        # Process: Extract by Mask (Extract by Mask) (sa)
        popdensity_2020_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Population\\popdensity_2020.tif"
        Extract_by_Mask = popdensity_2020_tif
        popdensity_2020_tif = arcpy.sa.ExtractByMask(gpw_v4_population_density_rev11_2020_30_sec_tif, BGD_adm0_1km_tif, "INSIDE", "DEFAULT")
        popdensity_2020_tif.save(Extract_by_Mask)


        # Process: Raster Calculator (2) (Raster Calculator) (sa)
        population_risk_2020_1_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Population\\population_risk_2020_1.tif"
        Raster_Calculator_2_ = population_risk_2020_1_tif
        population_risk_2020_1_tif = Con((popdensity_2020_tif >=  50) & (popdensity_2020_tif <  1300), 1)
        population_risk_2020_1_tif.save(Raster_Calculator_2_)


        # Process: Raster Calculator (22) (Raster Calculator) (sa)
        population_risk_2020_0_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Population\\population_risk_2020_0.tif"
        Raster_Calculator_22_ = population_risk_2020_0_tif
        population_risk_2020_0_tif = Con((popdensity_2020_tif  >=  0) & (popdensity_2020_tif  <  50), 0)
        population_risk_2020_0_tif.save(Raster_Calculator_22_)


        # Process: Raster Calculator (3) (Raster Calculator) (sa)
        population_risk_2020_2_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Population\\population_risk_2020_2.tif"
        Raster_Calculator_3_ = population_risk_2020_2_tif
        population_risk_2020_2_tif = Con((popdensity_2020_tif  >=  1300) & (popdensity_2020_tif  <  1500), 2)
        population_risk_2020_2_tif.save(Raster_Calculator_3_)


        # Process: Raster Calculator (4) (Raster Calculator) (sa)
        population_risk_2020_3_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Population\\population_risk_2020_3.tif"
        Raster_Calculator_4_ = population_risk_2020_3_tif
        population_risk_2020_3_tif = Con((popdensity_2020_tif  >=  1500) & (popdensity_2020_tif  <  1600), 3)
        population_risk_2020_3_tif.save(Raster_Calculator_4_)


        # Process: Raster Calculator (5) (Raster Calculator) (sa)
        population_risk_2020_4_tif = "D:\\RFF-GABS Project\\Bangladesh\\Temporary Files_Model BD\\Population\\population_risk_2020_4.tif"
        Raster_Calculator_5_ = population_risk_2020_4_tif
        population_risk_2020_4_tif = Con((popdensity_2020_tif  >=  1600), 4)
        population_risk_2020_4_tif.save(Raster_Calculator_5_)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        population_2020_tif = arcpy.management.MosaicToNewRaster(input_rasters=[population_risk_2020_1_tif, population_risk_2020_0_tif, population_risk_2020_2_tif, population_risk_2020_3_tif, population_risk_2020_4_tif], output_location=Population, raster_dataset_name_with_extension="population_2020.tif", pixel_type="8_BIT_UNSIGNED", cellsize=0.0083333333, number_of_bands=1, mosaic_method="MEAN")[0]
        population_2020_tif = arcpy.Raster(population_2020_tif)

        # Process: Extract by Mask (2) (Extract by Mask) (sa)
        population_risk_2020_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Population\\population_risk_2020.tif"
        Extract_by_Mask_2_ = population_risk_2020_tif
        population_risk_2020_tif = arcpy.sa.ExtractByMask(population_2020_tif, population_2020_tif, "INSIDE", "DEFAULT")
        population_risk_2020_tif.save(Extract_by_Mask_2_)


        # Process: Weighted Sum (Weighted Sum) (sa)
        Model_BD_Cholera_Risk_Jul_2022_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Monthly Cholera Risk\\JUL_2022\\Model BD_Cholera_Risk_Jul_2022.tif"
        Weighted_Sum = Model_BD_Cholera_Risk_Jul_2022_tif
        Model_BD_Cholera_Risk_Jul_2022_tif = arcpy.sa.WeightedSum(WSTable([[Elevation_Risk_tif, 'Value', 0.1], [Temperature_Risk_Jun_2022_clip_tif, 'VALUE', 0.1], [Temp_Forecast_Jul_2022_clip_tif, 'VALUE', 0.1], [Rain_Anomaly_Risk_Jun_2022_clip_tif, 'VALUE', 0.15], [Rain_F_Risk_Jul_2022_clip_tif, 'VALUE', 0.15], [Jun_avg_Cholera_Risk_clip_tif, 'VALUE', 0.2], [population_risk_2020_tif, 'VALUE', 0.2]]))
        Model_BD_Cholera_Risk_Jul_2022_tif.save(Weighted_Sum)


        # Process: Rescale by Function (Rescale by Function) (sa)
        Model_BD_Cholera_Risk_Jul_2022_Rescale_tif = "D:\\RFF-GABS Project\\Bangladesh\\Final Output_Raster_Shapefile_Model BD\\Monthly Cholera Risk\\JUL_2022\\Model BD_Cholera_Risk_Jul_2022_Rescale.tif"
        Rescale_by_Function = Model_BD_Cholera_Risk_Jul_2022_Rescale_tif
        Model_BD_Cholera_Risk_Jul_2022_Rescale_tif = arcpy.sa.RescaleByFunction(Model_BD_Cholera_Risk_Jul_2022_tif, [["LINEAR", 0, "", 4, "", 0, 4, ""]], 0, 1)
        Model_BD_Cholera_Risk_Jul_2022_Rescale_tif.save(Rescale_by_Function)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject31\\CholeraMap.gdb", workspace="C:\\Users\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject31\\CholeraMap.gdb"):
        Model()
